[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "epicsarchiverapdocs"
authors = [{name = "Sky Brewer", email = "sky.brewer@ess.eu"}]
dynamic = ["version", "description"]
